name: "terraform-destroy"
description: "Destroys a terraform configuration"
inputs:
  region:
    description: "aws region name"
    required: true
  access-key:
    description: "access key"
    required: true
  secret-key:
    description: "secret key"
    required: true
  terraform-folder:
    description: "folder where your terraform configuration is"
    required: true
  environment:
    description: "3 letter word to define the environment to deploy."
    required: true

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/../terraform-destroy.sh ${{ inputs.region }} ${{ inputs.access-key }} ${{ inputs.secret-key }} ${{ inputs.terraform-folder }} ${{ inputs.environment }} ${{ inputs.terraform-var-file }} ${{ inputs.terraform-plan-file }}
      shell: bash